export const Routes = {
  home: "/",
  trips: "/trips",
  inbox: "/inbox",
  favorites: "/favorites",
  more: "/more",
  searchResults: "/search-results",
  searchMap: "/search-map",
  filters: "/filters",
  vehicle: (id: string) => `/vehicle/${id}`,
  bookingDates: (id: string) => `/booking/${id}/dates`,
  bookingPickup: (id: string) => `/booking/${id}/pickup`,
  bookingProtection: (id: string) => `/booking/${id}/protection`,
  bookingCheckout: (id: string) => `/booking/${id}/checkout`,
  bookingConfirmation: (id: string) => `/booking/${id}/confirmation`,
  tripDetail: (id: string) => `/trip/${id}`,
  inboxThread: (id: string) => `/inbox-thread/${id}`,
  company: (id: string) => `/company/${id}`,
  companyFleet: (id: string) => `/company/${id}/fleet`,
  companyShare: (id: string) => `/company/${id}/share`,
  becomeHost: "/become-host",
  becomeHostVehicle: "/become-host/vehicle-details",
  becomeHostPhotos: "/become-host/photos",
  becomeHostLocation: "/become-host/location",
  becomeHostPricing: "/become-host/pricing",
  becomeHostPublish: "/become-host/publish",
  componentLibrary: "/dev/component-library",
} as const;
